database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: "password@123"
  url: jdbc:mysql://localhost:3306/FlipFitDB
  properties:
    charSet: UTF-8
    serverTimezone: UTC
    allowPublicKeyRetrieval: true
    useSSL: false

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
